"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, Clock3, Dumbbell, History, Pause, Play, RotateCcw } from "lucide-react";

type HubItem = { id: string; content_type: "workout_plan"; title: string; summary: string; payload: Record<string, unknown>; content_date: string };
type ActionState = { item_id: string; action_key: string; completed: boolean };
type Exercise = { key: string; title: string; detail: string; phase: string; seconds: number; reps: string };
const TEXT = "#465a6b"; const SURFACE = "#cfe7f1"; const ACCENT = "#ffd8b8";
const defaultPlan = [
  { id: "warm-1", title: "髋部与臀腿动态热身", summary: "髋关节画圈、腿后侧动态拉伸，动作轻柔。", phase: "热身", durationSeconds: 180, reps: "3 分钟" },
  { id: "main-1", title: "臀桥", summary: "脚掌踩稳，收紧臀部；避免腰部代偿。", phase: "主训练", durationSeconds: 90, reps: "12 次 × 3 组" },
  { id: "main-2", title: "跪姿后抬腿", summary: "左右交替，骨盆保持稳定，膝盖垫上软垫。", phase: "主训练", durationSeconds: 120, reps: "每侧 12 次 × 2 组" },
  { id: "main-3", title: "侧卧蚌式开合", summary: "上身不后仰，缓慢打开与收回。", phase: "主训练", durationSeconds: 120, reps: "每侧 15 次 × 2 组" },
  { id: "cool-1", title: "臀肌与髋屈肌拉伸", summary: "保持自然呼吸，不做疼痛拉伸。", phase: "拉伸", durationSeconds: 180, reps: "每侧 45 秒 × 2" },
];
function today() { return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Shanghai", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date()); }
function exercisesFrom(item?: HubItem): Exercise[] {
  const rows = Array.isArray(item?.payload.items) ? item.payload.items : [];
  if (!rows.length) return defaultPlan.map((row) => ({ key: row.id, title: row.title, detail: row.summary, phase: row.phase, seconds: row.durationSeconds, reps: row.reps }));
  return rows.map((entry, index) => { const value = typeof entry === "object" && entry ? entry as Record<string, unknown> : {}; return { key: String(value.id ?? index), title: String(value.title ?? value.text ?? `训练动作 ${index + 1}`), detail: String(value.summary ?? value.detail ?? "完成动作后点击打勾。"), phase: String(value.phase ?? (index === 0 ? "热身" : "主训练")), seconds: Math.max(15, Number(value.durationSeconds ?? value.seconds ?? 60)), reps: String(value.reps ?? value.durationLabel ?? "按计划完成") }; });
}
function formatTime(value: number) { const minutes = Math.floor(Math.max(0, value) / 60); const seconds = Math.max(0, value) % 60; return `${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}`; }

export default function TrainingPage() {
  const [date] = useState(today); const [item, setItem] = useState<HubItem | null>(null); const [actions, setActions] = useState<ActionState[]>([]); const [history, setHistory] = useState<HubItem[]>([]); const [historyActions, setHistoryActions] = useState<ActionState[]>([]); const [error, setError] = useState(""); const [seeding, setSeeding] = useState(false);
  const [activeKey, setActiveKey] = useState(""); const [seconds, setSeconds] = useState(0); const [running, setRunning] = useState(false); const [editedSeconds, setEditedSeconds] = useState<Record<string, number>>({});
  const request = useCallback(async (url: string, init?: RequestInit) => { const token = localStorage.getItem("suci_access_token") || ""; if (!token) throw new Error("请先从「溯 · 辞」登录，再打开训练。"); const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}`, ...(init?.headers || {}) } }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "同步失败"); return body; }, []);
  const load = useCallback(async () => { try { const [daily, old] = await Promise.all([request(`/api/daily-hub?date=${date}`), request("/api/daily-hub?history=workout")]); setItem((daily.items || []).find((entry: HubItem) => entry.content_type === "workout_plan") || null); setActions(daily.actions || []); setHistory(old.items || []); setHistoryActions(old.actions || []); } catch (cause) { setError(cause instanceof Error ? cause.message : "无法读取训练内容"); } }, [date, request]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { if (!running) return; const timer = window.setInterval(() => setSeconds((value) => { if (value <= 1) { setRunning(false); return 0; } return value - 1; }), 1000); return () => window.clearInterval(timer); }, [running]);
  const exercises = useMemo(() => exercisesFrom(item || undefined).map((exercise) => ({ ...exercise, seconds: editedSeconds[exercise.key] ?? exercise.seconds })), [item, editedSeconds]);
  const completed = exercises.filter((exercise) => actions.some((state) => state.item_id === item?.id && state.action_key === exercise.key && state.completed)).length;
  const active = exercises.find((exercise) => exercise.key === activeKey) || null;
  async function seedPlan() { setSeeding(true); try { const data = await request("/api/daily-hub", { method: "POST", body: JSON.stringify({ action: "upsert-content", contentType: "workout_plan", contentDate: date, title: "Day 2｜臀腿激活与线条训练", summary: "低冲击臀腿训练，保护膝盖；包含热身、主训练与拉伸。", payload: { items: defaultPlan }, importSource: "dailyglow_default_day2" }) }); setItem(data.item); setActions([]); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "创建今日训练失败"); } finally { setSeeding(false); } }
  async function toggle(exercise: Exercise, checked: boolean) { if (!item) return; setActions((old) => [...old.filter((state) => !(state.item_id === item.id && state.action_key === exercise.key)), { item_id: item.id, action_key: exercise.key, completed: checked }]); try { await request("/api/daily-hub", { method: "POST", body: JSON.stringify({ action: "set-action-state", itemId: item.id, actionKey: exercise.key, completed: checked }) }); } catch (cause) { setError(cause instanceof Error ? cause.message : "保存失败"); void load(); } }
  async function finish() { if (!item) return; await Promise.all(exercises.filter((exercise) => !actions.some((state) => state.item_id === item.id && state.action_key === exercise.key && state.completed)).map((exercise) => toggle(exercise, true))); }
  function start(exercise: Exercise) { setActiveKey(exercise.key); setSeconds(exercise.seconds); setRunning(true); }
  return <main className="min-h-screen bg-[#f9f2ef]" style={{ color: TEXT }}>
    <header className="border-b border-[#eadfd9] bg-[#fffdfb]"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><Link href="/daily" className="flex items-center gap-2 font-black"><span className="grid h-9 w-9 place-items-center rounded-2xl" style={{ backgroundColor: SURFACE }}>D</span>DailyGlow</Link><nav className="hidden items-center gap-5 text-sm font-semibold md:flex"><Link href="/daily">每日中心</Link><Link href="/">溯 · 辞</Link><Link href="/insights">洞察</Link><Link className="rounded-full px-3 py-1" style={{ backgroundColor: ACCENT }} href="/training">训练</Link></nav><Link href="/daily" className="text-sm font-bold">返回总览</Link></div></header>
    <section className="mx-auto max-w-6xl px-5 py-9"><Link href="/daily" className="inline-flex items-center gap-1 text-sm font-bold text-[#5e7180]"><ArrowLeft size={16}/>每日中心</Link><div className="mt-5 flex flex-wrap items-end justify-between gap-5"><div><p className="flex items-center gap-2 text-sm font-bold"><Dumbbell size={16}/>今日训练</p><h1 className="mt-2 text-3xl font-black md:text-5xl">练完今天，慢慢变强。</h1><p className="mt-3 text-[#5e7180]">{date} · 已完成 {completed} / {exercises.length} 项</p></div><div className="rounded-2xl bg-[#fffdfb] px-5 py-3 text-sm font-bold">低冲击 · 保护膝盖</div></div>
      {error && <p className="mt-6 rounded-2xl border border-[#fcceb4] bg-[#fffaf7] px-4 py-3 text-sm">{error}</p>}
      {!item && <section className="mt-8 rounded-[2rem] border border-[#eadfd9] bg-[#fffdfb] p-6 md:p-8"><p className="inline-flex rounded-full px-3 py-1 text-sm font-bold" style={{ backgroundColor: ACCENT }}>备用训练计划</p><h2 className="mt-3 text-2xl font-black">今天的自动训练尚未抵达</h2><p className="mt-2 max-w-xl leading-7 text-[#5e7180]">可先导入你的 Day 2 臀腿激活计划；定时任务抵达后仍可替换为当天正式训练。</p><button disabled={seeding} onClick={() => void seedPlan()} className="mt-5 inline-flex items-center gap-2 rounded-full px-5 py-3 text-sm font-bold" style={{ backgroundColor: SURFACE }}><Dumbbell size={17}/>{seeding ? "正在导入…" : "开始 Day 2 训练"}</button></section>}
      {item && <><section className="mt-8 grid gap-5 lg:grid-cols-[minmax(0,1fr)_21rem]"><div className="overflow-hidden rounded-[2rem] border border-[#eadfd9] bg-[#fffdfb]"><div className="bg-[#d2e0aa] p-6"><p className="text-sm font-bold">本次计划</p><h2 className="mt-1 text-2xl font-black">{item.title}</h2><p className="mt-2 text-sm leading-6">{item.summary}</p></div><div className="space-y-4 p-5 md:p-6">{["热身", "主训练", "拉伸"].map((phase) => { const group = exercises.filter((exercise) => exercise.phase === phase); if (!group.length) return null; return <div key={phase}><p className="mb-2 text-sm font-black text-[#5e7180]">{phase}</p><div className="space-y-3">{group.map((exercise) => { const checked = actions.some((state) => state.item_id === item.id && state.action_key === exercise.key && state.completed); return <article key={exercise.key} className="rounded-2xl border border-[#eadfd9] bg-[#fffdfb] p-4"><div className="flex gap-3"><input aria-label={`完成 ${exercise.title}`} checked={checked} onChange={(event) => void toggle(exercise, event.target.checked)} type="checkbox" className="mt-1 h-4 w-4" style={{ accentColor: ACCENT }}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className={checked ? "font-black line-through opacity-55" : "font-black"}>{exercise.title}</h3><p className="mt-1 text-sm leading-6 text-[#697386]">{exercise.detail}</p></div><button onClick={() => start(exercise)} className="inline-flex shrink-0 items-center gap-1 rounded-full px-3 py-2 text-sm font-bold" style={{ backgroundColor: SURFACE }}><Play size={15}/>开始计时</button></div><div className="mt-3 flex flex-wrap items-center gap-3 text-sm"><label className="flex items-center gap-2 text-[#5e7180]">时长 <input value={Math.round(exercise.seconds / 60)} min="1" onChange={(event) => setEditedSeconds((old) => ({ ...old, [exercise.key]: Math.max(1, Number(event.target.value || 1)) * 60 }))} type="number" className="w-16 rounded-lg border border-[#eadfd9] bg-white px-2 py-1 text-center font-bold"/> 分钟</label><span className="rounded-full bg-[#fff1e4] px-3 py-1 font-bold">{exercise.reps}</span></div></div></div></article>; })}</div></div>; })}</div></div>
        <aside className="rounded-[2rem] border border-[#eadfd9] bg-[#fffdfb] p-6"><p className="inline-flex rounded-full px-3 py-1 text-sm font-bold" style={{ backgroundColor: SURFACE }}>动作计时</p>{active ? <><p className="mt-6 text-sm font-bold text-[#5e7180]">正在进行</p><h2 className="mt-1 text-xl font-black">{active.title}</h2><div className="mt-5 text-5xl font-black tracking-tight">{formatTime(seconds)}</div><div className="mt-5 flex gap-2"><button onClick={() => setRunning((value) => !value)} className="inline-flex flex-1 items-center justify-center gap-2 rounded-full px-4 py-3 text-sm font-bold" style={{ backgroundColor: SURFACE }}>{running ? <><Pause size={16}/>暂停</> : <><Play size={16}/>继续</>}</button><button onClick={() => { setSeconds(active.seconds); setRunning(false); }} className="grid h-11 w-11 place-items-center rounded-full border border-[#eadfd9]" aria-label="重置"><RotateCcw size={17}/></button></div><button onClick={() => { void toggle(active, true); setRunning(false); }} className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-full px-4 py-3 text-sm font-bold" style={{ backgroundColor: ACCENT }}><Check size={17}/>完成本动作</button></> : <div className="mt-6 rounded-2xl bg-[#f7fbfd] p-5 text-sm leading-7 text-[#5e7180]"><Clock3 size={22}/><p className="mt-3">从左侧选择动作即可开始倒计时。可暂停、重置，也可在完成时直接打勾。</p></div>}<button onClick={() => void finish()} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-full border border-[#eadfd9] px-4 py-3 text-sm font-bold"><Check size={17}/>完成训练并打卡</button></aside></section>
        <section className="mt-8 rounded-[2rem] border border-[#eadfd9] bg-[#fffdfb] p-6 md:p-8"><div className="flex items-center gap-2"><History size={20}/><div><p className="text-sm font-bold">训练历史</p><h2 className="text-xl font-black">最近的完成情况</h2></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{history.slice(0, 8).map((old) => { const total = exercisesFrom(old).length; const done = historyActions.filter((state) => state.item_id === old.id && state.completed).length; return <div key={old.id} className="rounded-2xl bg-[#f7fbfd] p-4"><p className="text-xs font-bold text-[#697386]">{old.content_date}</p><p className="mt-2 font-black">{old.title}</p><p className="mt-2 text-sm text-[#5e7180]">完成 {Math.min(done, total)} / {total} 项</p></div>; })}{!history.length && <p className="text-sm text-[#697386]">完成今天训练后，历史会显示在这里。</p>}</div></section></>}
    </section></main>;
}
